[package]
name = "wado"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bitflags = "2"
x264 = "0.5"

[dependencies.smithay]
git = "https://github.com/Smithay/smithay.git"
default-features = false
features = [
    "renderer_gl",
    "wayland_frontend",
    "desktop",
]
